jobs:
  - name: dataworks-mastered-data-qa
    plan:
      - in_parallel:
          - get: dataworks-mastered-data
            trigger: true
      - .: (( inject meta.plan.vcs-to-s3 ))
        config:
          params:
            AWS_ROLE_ARN: ((aws_account.qa))
            S3_BUCKET: ((dataworks.bucket-list.qa.published))
            RESOURCE_ROOT: pdm/hive/data/
            S3_ROOT: common-model-inputs/
          inputs:
            - name: dataworks-mastered-data
