jobs:
  - name: dataworks-mastered-data-production
    plan:
      - in_parallel:
          - get: dataworks-mastered-data
            trigger: true
      - .: (( inject meta.plan.vcs-to-s3 ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            S3_BUCKET: ((dataworks.bucket-list.production.published))
            RESOURCE_FILES: "*.csv"
            RESOURCE_ROOT: pdm/hive/data/
            S3_ROOT: common-model-inputs/
          inputs:
            - name: dataworks-mastered-data
