jobs:
  - name: ucfs-mastered-data-qa
    plan:
      - in_parallel:
          - get: ucfs-mastered-data
            trigger: true
      - .: (( inject meta.plan.vcs-to-s3 ))
        config:
          params:
            AWS_ROLE_ARN: ((aws_account.qa))
            S3_BUCKET: ((dataworks.bucket-list.qa.published))
            RESOURCE_FILES: "*.json"
            RESOURCE_ROOT: organisation/src/main/resources/
            S3_ROOT: common-model-inputs/
          inputs:
            - name: ucfs-mastered-data
