jobs:
  - name: ucfs-mastered-data-integration
    plan:
      - in_parallel:
          - get: ucfs-mastered-data
            trigger: true
      - .: (( inject meta.plan.vcs-to-s3 ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            S3_BUCKET: ((dataworks.bucket-list.integration.published))
            RESOURCE_FILES: "*.json"
            RESOURCE_ROOT: organisation/src/main/resources/
            S3_ROOT: common-model-inputs/
          inputs:
            - name: ucfs-mastered-data
