jobs:
  - name: pdm-dataset-generation-preprod
    plan:
      - in_parallel:
          - get: aws-pdm-dataset-generation
            trigger: false
            passed:
              - pdm-dataset-generation-integration
          - get: emr-launcher-release
            trigger: false
            passed:
              - pdm-dataset-generation-integration
          - get: emr-ami
            trigger: false
            passed:
              - pdm-dataset-generation-integration
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
