jobs:
  - name: qa-start-cluster
    plan:
      - get: aws-pdm-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            S3_PREFIX: analytical-dataset/2020-08-18_07-01-37/
            CORRELATION_ID: test
