jobs:
  - name: prod-start-cluster
    plan:
      - get: aws-pdm-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: analytical-dataset/full/2021-04-01_09-40-02
            CORRELATION_ID: ingest_emr_scheduled_tasks_export_snapshots_to_crown_production_full_114_full
            SNAPSHOT_TYPE: "full"
            EXPORT_DATE: "2021-04-01"
