groups:
- jobs:
  - object-tagging-dev
  name: object-tagging
jobs:
- name: object-tagging-dev
  plan:
  - get: dataworks-s3-object-tagger
    trigger: true
  - get: meta
  - attempts: 1
    config:
      image_resource:
        source:
          repository: ((dataworks.docker_awscli_repository))
          tag: ((dataworks.docker_awscli_version))
          version: ((dataworks.docker_awscli_version))
        type: docker-image
      inputs:
      - name: meta
      params:
        AWS_DEFAULT_REGION: eu-west-2
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
        BATCH_JOB_DEFINITION: pdm_object_tagger_job
        TIMEOUT: 90
      platform: linux
      run:
        args:
        - -exc
        - |
          source /assume-role
          pipeline_name=`cat "meta/build_pipeline_name"`
          job_name=`cat "meta/build_job_name"`
          build_number=`cat "meta/build_name"`
          job_id=$(aws batch submit-job --job-queue pdm_object_tagger --job-definition ${BATCH_JOB_DEFINITION} \
            --job-name ${pipeline_name}_${job_name}_${build_number} \
            --parameters manifest='{"test": "test_pipeline"}' \
            | jq -e --raw-output .jobId)
          i=0
          set +x
          while [[ ${i} -le ${TIMEOUT} ]]
          do
            status=$(aws batch describe-jobs --jobs ${job_id} | jq -e --raw-output '.jobs[0].status')
            if [ "$status" == "FAILED" ]; then
              echo "job failed"
              exit 1
            fi
            if [ "$status" == "SUCCEEDED" ]; then
              echo "job succeeded"
              exit 0
            fi
            echo "job is currently ${status}"
            i=$((i+1))
            sleep 60
          done
          exit 1
        path: sh
    task: object-tagging-batch
  serial: true
resource_types:
- name: meta
  source:
    repository: olhtbr/metadata-resource
    tag: 2.0.1
  type: docker-image
resources:
- check_every: 5m
  name: dataworks-s3-object-tagger
  source:
    branch: master
    repository: dwp/dataworks-s3-object-tagger
    uri: https://github.com/dwp/dataworks-s3-object-tagger.git
  type: git
  webhook_token: ((dataworks.concourse_github_webhook_token))
- name: meta
  type: meta
