jobs:
- name: pdm-dataset-generation-dev
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      resource: aws-pdm-dataset-generation-emr-6
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: emr-relauncher-release
      trigger: true
    - get: emr-al2-ami
      trigger: true
    - get: dataworks-behavioural-framework
      trigger: false
    - put: meta
      resource: meta-development
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.development))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: default

