jobs:
- name: pdm-dataset-generation-dev
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      trigger: true
    - get: emr-launcher-release
      version: { tag: ((emr-launcher-version.development)) }
      trigger: true
    - get: emr-relauncher-release
      version: { tag: ((emr-relauncher-version.development)) }
      trigger: true
    - get: al2-emr-ami
      trigger: true
    - get: dataworks-behavioural-framework
      trigger: false
    - put: meta
      resource: meta-development
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.development))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.run-behave-job ))
    config:
      params:
        E2E_FEATURE_TAG_FILTER: aws-pdm-dataset-generation
        AWS_ACC: ((aws_account.development))
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
