jobs:
- name: pdm-dataset-generation-dev
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: emr-al2-ami
      trigger: true
    - get: aws-ingestion
    - get: aws-common-infrastructure
    - get: aws-internal-compute
    - get: aws-dataworks-e2e-framework
    - put: meta
      resource: meta-development
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.development))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: default
  - in_parallel:
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: default
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: default
    - .: (( inject meta.plan.terraform-output-common ))
      params:
        TF_WORKSPACE: default
  - .: (( inject meta.plan.run-behave-job ))
    config:
      params:
        E2E_FEATURE_TAG_FILTER: aws-pdm-dataset-generation
        AWS_ACC: ((aws_account.development))
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
