jobs:
  - name: object-tagging-dev
    serial: true
    plan:
      - aggregate:
          - put: meta
            resource: meta-development
          - get: dataworks-s3-object-tagger
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ROLE: arn:aws:iam::((aws_account.development)):role/ci
            AWS_REGION: eu-west-2
      - .: (( inject meta.plan.object-tagging-batch ))
        config:
          params:
            BATCH_JOB_DEFINITION: pdm_object_tagger_job
