jobs:
  - name: rbac-csv-upload-qa
    max_in_flight: 1
    serial: true
    plan:
      - get: rbac-csv
        trigger: true
        passed:
        - rbac-csv-upload-dev
      - get: aws-common-infrastructure
      - .: (( inject meta.plan.terraform-output ))
        config:
          params:
            TF_WORKSPACE: qa
      - .: (( inject meta.plan.rbac-csv-upload ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci