jobs:
  - name: preprod-start-cluster
    plan:
      - get: aws-pdm-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            S3_PREFIX: analytical-dataset/2020-09-24_11-26-06/
            CORRELATION_ID: test
