jobs:
- name: pdm-dataset-generation-preprod
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      trigger: true
      passed:
      - pdm-dataset-generation-qa
    - get: dataworks-aws-s3-object-tagger-locals
      trigger: true
      passed:
        - pdm-dataset-generation-qa
    - get: emr-launcher-release
      trigger: true
      passed:
      - pdm-dataset-generation-qa
    - get: emr-relauncher-release
      trigger: true
      passed:
      - pdm-dataset-generation-qa
    - get: al2-emr-ami
      trigger: true
      passed:
      - pdm-dataset-generation-qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.preprod))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: preprod
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: preprod
