jobs:
  - name: pdm-dataset-generation-dev
    plan:
      - in_parallel:
          - get: aws-pdm-dataset-generation
            trigger: false
          - get: emr-launcher-release
            trigger: false
          - get: emr-ami
            trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
