jobs:
  - name: update-pipeline
    plan:
      - get: aws-pdm-dataset-generation
        resource: aws-pdm-dataset-generation-update-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
            dir: aws-pdm-dataset-generation
          inputs:
            - name: aws-pdm-dataset-generation
          outputs:
            - name: pipeline
      - set_pipeline: pdm-dataset-generation
        file: pipeline/aviator_pipeline.yml
