jobs:
  - name: dev-start-cluster
    plan:
      - get: aws-pdm-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            AWS_ACC: ((aws_account.development))
            S3_PREFIX: analytical-dataset/2020-08-14_09-43-10
            CORRELATION_ID: test
