jobs:
- name: pdm-dataset-generation-qa
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: emr-al2-ami
      trigger: true
    - get: aws-ingestion
    - get: aws-common-infrastructure
    - get: aws-internal-compute
    - get: aws-dataworks-e2e-framework
    - put: meta
      resource: meta-qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: qa
