jobs:
- name: pdm-dataset-generation-qa
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: aws-pdm-dataset-generation
      resource: aws-pdm-dataset-generation-emr-6
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: emr-relauncher-release
      trigger: true
    - get: emr-al2-ami
      trigger: true
    - get: dataworks-behavioural-framework
      trigger: false
    - put: meta
      resource: meta-qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.run-behave-job ))
    config:
      params:
        E2E_FEATURE_TAG_FILTER: aws-pdm-dataset-generation
        AWS_ACC: ((aws_account.qa))
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
